version: "3"

services:
  rutube_rag:
    build: .
    ports:
      - "31000:31000"
    network_mode: host
    environment:
      PROXY: ${PROXY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./checkpoints/retriever/:/app/retriever/checkpoints/
      - ./checkpoints/reranker/:/app/reranker/checkpoints/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]