DATA_PATH: 'data/all_data_with_docs.csv'
RETRIEVER:
    RETRIEVAL_MODEL_PATHS:
        - '/app/retriever/checkpoints/bge-m3-fold_1/'
        - '/app/retriever/checkpoints/bge-m3-fold_2/'
        - '/app/retriever/checkpoints/bge-m3-fold_3/'
        - '/app/retriever/checkpoints/bge-m3-fold_4/'
        - '/app/retriever/checkpoints/bge-m3-fold_5/'
    TOKENIZER_PATH: '/app/retriever/checkpoints/bge-m3-fold_1/'
RERANKER:
    RERANKER_MODEL_PATHS:
        - '/app/reranker/checkpoints/FacebookAI/xlm-roberta-large_fold_0/'
        - '/app/reranker/checkpoints/FacebookAI/xlm-roberta-large_fold_1/'
        - '/app/reranker/checkpoints/FacebookAI/xlm-roberta-large_fold_2/'
    TOKENIZER_PATH: '/app/reranker/checkpoints/FacebookAI/xlm-roberta-large_fold_0/'
    NUM_CLASSES: 3
    max_len: 256
RAG:
    bm25_retrieve_k: 2
    vectors_retrieve_k: 3
LLM:
    LLM_BASE_URL: 'http://localhost:8000/v1'
    MODEL_NAME: 'Vikhrmodels/Vikhr-Nemo-12B-Instruct-R-21-09-24'
    temperature: 0.5